function data = getDeploymentInfoLocal(input_file)

    data = readcsv_generic(input_file);
%     data = [
% %     (struct ('deployment_id','1','deployment_name',...
% %      'SN651 glider data on 20170719 deployment',...
% %     'deployment_start',datenum('2017-07-24'),...
% %     'deployment_end', datenum('2017-08-20'), 'glider_name',...
% %     'Slocum_651', 'glider_serial', '651', 'glider_model', 'slocum_g2', ...
% %     'platform_maker', 'Teledyne-Webb research', ...
% %     'firmware_version_navigation', 'Unknown',...
% %     'wmo_platform_code', '4800995', 'platform_code', 'Slocum_651',...
% %     'principal_investigator', 'Tetjana Ross', 'institution_references', ...
% %     'http://www.pac.dfo-mpo.gc.ca/science/index-eng.html', ...
% %     'trans_system', 'Iridium, Argos',...
% %     'positioning_system', 'GPS, Iridium, Argos', ...
% %     'trans_system_id', '9899169234001823475, 172147',...
% %     'firmware_version_science',' ', ...
% %     'manual_version', ' ', 'wmo_inst_type', '846',...
% %     'battery_type', 'ALKALINE', ...
% %     'battery_PACKS', 'assy 4405', ...
% %     'platform_family', 'Open ocean glider, G2',...
% %     'deployment_platform', 'J.P. Tully',...
% %     'deployment_cruise_id', '18DD17037', ...
% %     'deployment_reference_station_id', 'P14'))];
% 
     (struct ('deployment_id','M36','deployment_name',...
     'SEA019 glider data on Test_BedfordBasin deployment',...
    'deployment_start',datenum('2018-02-14'),...
    'deployment_end', datenum('2018-02-22'), 'glider_name',...
    'SEA019', 'glider_serial', '019', 'glider_model', 'SeaExplorer', ...
    'platform_maker', 'ALSEAMAR', 'firmware_version_navigation', 'Unknown',...
    'wmo_platform_code', '48925', 'platform_code', 'SEA019',...
    'principal_investigator', 'Dave Hebert', 'institution_references', ...
    'www.dfo-mpo.gc.ca', 'trans_system', 'Iridium, Argos',...
    'positioning_system', 'GPS, Iridium, Argos', 'firmware_version_science',...
    '1.2.1', 'manual_version', 'v1.2', 'wmo_inst_type', '830',...
    'battery_type', 'Lithium ION', 'platform_family', 'Open ocean glider'))];

%      ; (struct ('deployment_id','M28','deployment_name',...
%      'SEA019 glider data on Test_BedfordBasin deployment',...
%     'deployment_start',datenum('2017-06-21'),...
%     'deployment_end', datenum('2017-06-22'), 'glider_name',...
%     'SEA019', 'glider_serial', '019', 'glider_model', 'SeaExplorer', ...
%     'platform_maker', 'ALSEAMAR', 'firmware_version_navigation', 'Unknown',...
%     'wmo_platform_code', '48925', 'platform_code', 'SEA019',...
%     'principal_investigator', 'Dave Hebert', 'institution_references', ...
%     'www.dfo-mpo.gc.ca', 'trans_system', 'Iridium, Argos',...
%     'positioning_system', 'GPS, Iridium, Argos', 'firmware_version_science',...
%     '1.2.1', 'manual_version', 'v1.2', 'wmo_inst_type', '830',...
%     'battery_type', 'Lithium ION', 'platform_family', 'Open ocean glider'))
%    
%     ];

%        (struct ('deployment_id',1,'deployment_name','ONC_TEST',...
%     'deployment_start',datenum('2016-07-25'),...
%     'deployment_end', datenum('2016-08-04'), 'glider_name',...
%     'SeaExplorer_003', 'glider_serial', '003', 'glider_model', 'SeaExplorer', ...
%     'wmo_platform_code', '4901800', 'platform_code', 'Sea_003'))];
%        (struct ('deployment_id',2,'deployment_name','ONC_TEST',...
%    'deployment_start',datenum('2017-01-28'),...
%    'deployment_end', datenum('2017-02-18'), 'glider_name',...
%    'skookum_346', 'glider_serial', '346', 'glider_model', 'slocum_g1',...
%    'wmo_platform_code', '4901801', 'platform_code', 'slocum_346'))];
   
end 